global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using MS.Pix.MED.Domain;
global using MS.Pix.Shared;
global using System.ComponentModel.DataAnnotations;
global using System.Text.Json.Serialization;
